### ISSUE TITLE
Main Page

### ISSUE THREAD

**Issue by isayahdurst** [isayahdurst/group-project-1#19]
As a user, I want a clean and polished main screen which displays my weekly meal plan and allows me to select recipes I would like to view.

It is done when:

I am able to view seven buttons (styled like calendars) which represent every day of the week M-F.

When I click one of the buttons, I am presented with three recipe cards which represent the meals for that day. 

Each card shows a thumbnail image of the recipe, a title of the meal, and a brief description of the recipe.

A button allows me to retrieve new recipes for a day in case I don't like any of the recipes that have been generated for me. 

A button allows me to change or edit my preferences so that I can change the types of recipes that are generated for me.

**Comment by AnthonyRLi** [comment]
Each M-F button should have 3 data-id attributes -- one for breakfast, one for lunch, one for dinner (e.g. data-idbreakfast, data-idlunch, data-iddinner). populated via javascript

Each recipe should have 1 data-attribute (data-id) for the recipe id -- this will be populated via javascript

When a recipe is clicked, we should pull all the recipe information from local storage based on the recipe id stored in data-id
